# -*- mode: python ; coding: utf-8 -*-
import os

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['src'],
    binaries=[],
    datas=[
        ('resources/categories.json', 'resources'),
    ],
    hiddenimports=[
        'config',
        'config.manager',
        'config.setup_wizard',
        'orchestrator',
        'orchestrator.processor',
        'utils',
        'utils.logger',
        'utils.hash_registry',
        'utils.exceptions',
        'utils.retry',
        'utils.auth',
        'drive',
        'drive.poller',
        'drive.models',
        'sheets',
        'sheets.generator',
        'llm',
        'llm.vision_categorizer',
        'llm.aggregator',
        'llm.vendor_cache',
        'llm.models',
        # Google API packages
        'google',
        'google.genai',
        'google.auth',
        'google.auth.transport',
        'google.auth.transport.requests',
        'google.oauth2',
        'google.oauth2.service_account',
        'google_auth_httplib2',
        'googleapiclient',
        'googleapiclient.discovery',
        'googleapiclient.http',
        'googleapiclient.errors',
        'googleapiclient.model',
        'googleapiclient._helpers',
        'gspread',
        'gspread.auth',
        'gspread.client',
        'gspread.spreadsheet',
        'gspread.worksheet',
        # Other dependencies
        'pydantic',
        'Levenshtein',
        'win32crypt',
        'win32api',
        'win32con',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='BudgetFlow',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version='version_info.txt',
    icon='resources/icon.ico' if os.path.exists('resources/icon.ico') else None,
)
